(deftheme chocolate
  "Created 2023-03-04. Inspired by coloufully decorated confection ")

(custom-theme-set-faces
 'chocolate
 '(cursor ((t (:background "peru"))))
 '(fixed-pitch ((t (:family "Monospace"))))
 '(variable-pitch ((((type w32)) (:foundry "outline" :family "Arial")) (t (:family "Sans Serif"))))
 '(escape-glyph ((((background dark)) (:foreground "cyan")) (((type pc)) (:foreground "magenta")) (t (:foreground "brown"))))
 '(homoglyph ((((background dark)) (:foreground "cyan")) (((type pc)) (:foreground "magenta")) (t (:foreground "brown"))))
 '(minibuffer-prompt ((t (:foreground "medium spring green" :weight bold))))
 '(highlight ((t (:background "OrangeRed4"))))
 '(region ((t (:extend t :background "saddle brown" :foreground "#faf4c6"))))
 '(shadow ((((class color grayscale) (min-colors 88) (background light)) (:foreground "grey50")) (((class color grayscale) (min-colors 88) (background dark)) (:foreground "grey70")) (((class color) (min-colors 8) (background light)) (:foreground "green")) (((class color) (min-colors 8) (background dark)) (:foreground "yellow"))))
 '(secondary-selection ((t (:extend t :background "black"))))
 '(trailing-whitespace ((t (:background "dark orchid"))))
 '(font-lock-builtin-face ((t (:weight bold :foreground "#9e0045"))))
 '(font-lock-comment-delimiter-face ((t (:inherit font-lock-comment-face))))
 '(font-lock-comment-face ((t (:foreground "rosy brown"))))
 '(font-lock-constant-face ((t (:foreground "deep pink"))))
 '(font-lock-doc-face ((t (:foreground "chocolate"))))
 '(font-lock-doc-markup-face ((t (:inherit (font-lock-constant-face)))))
 '(font-lock-function-name-face ((t (:foreground "green yellow" :weight bold))))
 '(font-lock-keyword-face ((t (:foreground "magenta" :weight bold))))
 '(font-lock-negation-char-face ((t (:foreground "#f03f3f"))))
 '(font-lock-preprocessor-face ((t (:inherit (font-lock-builtin-face)))))
 '(font-lock-regexp-grouping-backslash ((t (:inherit (bold)))))
 '(font-lock-regexp-grouping-construct ((t (:inherit (bold)))))
 '(font-lock-string-face ((t (:foreground "white smoke"))))
 '(font-lock-type-face ((t (:foreground "yellow"))))
 '(font-lock-variable-name-face ((t (:foreground "gold"))))
 '(font-lock-warning-face ((t (:foreground "#ffffff" :background "#ff6523"))))
 '(button ((t (:inherit (link)))))
 '(link ((t (:foreground "goldenrod"))))
 '(link-visited ((t (:foreground "violet" :inherit (link)))))
 '(fringe ((t (:foreground "#4c4c4c" :background "#f2f1c0"))))
 '(header-line ((t (:inherit mode-line :background "black" :foreground "magenta" :box nil))))
 '(tooltip ((t (:foreground "black" :background "lightyellow" :inherit (variable-pitch)))))
 '(mode-line ((t (:weight bold :foreground "#121212" :background "#f8f1b1"))))
 '(mode-line-buffer-id ((t (:weight bold :foreground "#424242" :background "#f8f0b0"))))
 '(mode-line-emphasis ((t (:weight bold))))
 '(mode-line-highlight ((t (:background "chocolate"))))
 '(mode-line-inactive ((t (:foreground "#616161" :background "#fcf9de"))))
 '(isearch ((t (:weight bold :foreground "#f03f3f" :background "#e2e2e5"))))
 '(isearch-fail ((((class color) (min-colors 88) (background light)) (:background "RosyBrown1")) (((class color) (min-colors 88) (background dark)) (:background "red4")) (((class color) (min-colors 16)) (:background "red")) (((class color) (min-colors 8)) (:background "red")) (((class color grayscale)) (:foreground "grey")) (t (:inverse-video t))))
 '(lazy-highlight ((t (:background "medium orchid"))))
 '(match ((((class color) (min-colors 88) (background light)) (:background "khaki1")) (((class color) (min-colors 88) (background dark)) (:background "RoyalBlue3")) (((class color) (min-colors 8) (background light)) (:foreground "black" :background "yellow")) (((class color) (min-colors 8) (background dark)) (:foreground "white" :background "blue")) (((type tty) (class mono)) (:inverse-video t)) (t (:background "gray"))))
 '(next-error ((t (:inherit region))))
 '(query-replace ((t (:inherit (isearch)))))
 '(default ((t (:inherit nil :extend nil :stipple nil :background "#2e1100" :foreground "cyan" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 128 :width normal :foundry "PfEd" :family "FantasqueSansMono Nerd Font")))))

(provide-theme 'chocolate)
